services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 13306:3306
      - 23306:33060
    volumes:
      - "../components/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    environment:
      MYSQL_ROOT_PASSWORD: openIM
    restart: always

  redis:
    image: redis:5.0.7
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - "../components/redis/data:/data"
      - "../components/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass openIM --appendonly yes

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "12181:2181"
  #   volumes:
  #     - "/etc/localtime:/etc/localtime"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - TZ="Asia/Shanghai"
  #   restart: always
  
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    environment:
      ETCDCTL_API: 3
    restart: always
    command: /usr/local/bin/etcd --name etcd0 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster etcd0=http://0.0.0.0:2380 --initial-cluster-token tkn --initial-cluster-state new
