services:
  redis:
    image: redis:5.0.7
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - "./components/redis/data:/data"
      - "./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass openIM --appendonly yes
